---
title: "Weight of Fish"
author: "Joel Calderin"
date: "Fall 2023`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
library(dplyr)
library(leaps)
fish = read.csv("Fish.csv")
```

# Predicting Fish Weight

Find the best model using two variables to predict Perch weight, and compare this to the best over-all model

## Perch
```{r}
Perch = filter(fish, Species == 'Perch')
```

## Best 2 Regressor Model 
```{r}
modelPerch = regsubsets(Weight ~ Length1 + Length2 + Length3 + Height + Width, data = Perch)
summary(modelPerch)
```

## Best 2-Variable predictor is Height and Width

```{r}
best2Perch= lm(Weight ~ Height + Width, data = Perch)
summary(best2Perch)
```

### Best 2-Variable equation
Weight = -536 + 74.77 * Height + 69.62 * Width


## Pike
```{r}
Pike = filter(fish, Species == 'Pike')
```

### Best Two regressor model

```{r}

```


## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements